import MRICardiacThumbnail from '@/src/assets/samples/MRI-Cardiac.jpg';
import MRIPROSTATExThumbnail from '@/src/assets/samples/MRI-PROSTATEx.jpg';
import MRAHeadThumbnail from '@/src/assets/samples/MRA-Head_and_Neck.jpg';
import CTAHeadThumbnail from '@/src/assets/samples/CTA-Head_and_Neck.jpg';
import USFetusThumbnail from '@/src/assets/samples/3DUS-Fetus.jpg';
import USCineThumbnail from '@/src/assets/samples/US-Cine.jpg';
import { SegmentMask } from '@/src/types/segment';
import type {
  SampleWorklistMetadata,
  SyntheticWorklistStudy,
} from '@/src/types/worklist';
import type { LayoutConfig } from './utils/layoutParsing';
import type { ViewInfoInit } from './types/views';
import { SampleDataset } from './types';
import { Action } from './constants';

/**
 * These are the initial view IDs.
 *
 * These view IDs get mapped to components in core/viewTypes.ts.
 */
export const InitViewIDs: Record<string, string> = {
  Coronal: 'Coronal',
  Sagittal: 'Sagittal',
  Axial: 'Axial',
  Three: '3D',
  ObliqueCoronal: 'ObliqueCoronal',
  ObliqueSagittal: 'ObliqueSagittal',
  ObliqueAxial: 'ObliqueAxial',
  ObliqueThree: 'Oblique3D',
};

export const getAvailableViews = () => {
  const list: ViewInfoInit[] = [
    {
      name: 'Oblique',
      type: 'Oblique',
      dataID: null,
      options: {},
    },
    {
      name: 'Volume',
      type: '3D',
      dataID: null,
      options: {
        viewDirection: 'Posterior',
        viewUp: 'Superior',
      },
    },
    {
      name: 'Coronal',
      type: '2D',
      dataID: null,
      options: {
        orientation: 'Coronal',
      },
    },
    {
      name: 'Sagittal',
      type: '2D',
      dataID: null,
      options: {
        orientation: 'Sagittal',
      },
    },
    {
      name: 'Axial',
      type: '2D',
      dataID: null,
      options: {
        orientation: 'Axial',
      },
    },
  ];

  const byName = list.reduce(
    (acc, view) => ({ ...acc, [view.name]: view }),
    {} as Record<string, ViewInfoInit>
  );

  return { list, byName };
};

export const DefaultNamedLayouts: Record<string, LayoutConfig> = {
  'Four Up': [
    ['axial', 'coronal'],
    ['sagittal', 'volume'],
  ],
  'Axial Coronal Sagittal': {
    direction: 'row',
    items: [
      'axial',
      {
        direction: 'column',
        items: ['coronal', 'sagittal'],
      },
    ],
  },
  'Axial Only': [['axial']],
  '3D Only': [['volume']],
  Oblique: [['oblique']],
  '3D Primary': {
    direction: 'row',
    items: [
      'volume',
      {
        direction: 'column',
        items: ['axial', 'coronal', 'sagittal'],
      },
    ],
  },
};

export const SAMPLE_DATA: SampleDataset[] = [
  {
    name: 'CTA Head and Neck',
    filename: 'CTA-Head_and_Neck.zip',
    description:
      'CTA head and neck scan of elderly patient with tumor. (80 MB)',
    url: 'https://data.kitware.com/api/v1/item/6347159711dab81428208e24/download',
    image: CTAHeadThumbnail,
  },
  {
    name: 'MRA Head and Neck',
    filename: 'MRA-Head_and_Neck.zip',
    description:
      'MRA from Patient Contributed Image Repository. Click application help icon "(?)" for more info. (15 MB)',
    url: 'https://data.kitware.com/api/v1/item/6352a2b311dab8142820a33b/download',
    image: MRAHeadThumbnail,
  },
  {
    name: 'MRI Cardiac 3D and Cine',
    filename: 'MRI-Cardiac-3D_and_Cine.zip',
    description:
      'MRI scan with two series: 3D axial non-gated and 2 chamber cine. (4 MB)',
    url: 'https://data.kitware.com/api/v1/item/6350b28f11dab8142820949d/download',
    image: MRICardiacThumbnail,
  },
  {
    name: 'MRI PROSTATEx',
    filename: 'MRI-PROSTATEx-0004.zip',
    description:
      'MRI from the SPIE-AAPM-NCI PROSTATEx challenge. Click application help "(?)" icon for more info. (3 MB)',
    url: 'https://data.kitware.com/api/v1/item/63527c7311dab8142820a338/download',
    image: MRIPROSTATExThumbnail,
  },
  {
    name: '3D US Fetus',
    filename: '3DUS-Fetus.mha',
    description:
      '3D ultrasound of a baby. Downloaded from tomovision.com.(8 MB)',
    url: 'https://data.kitware.com/api/v1/item/635679c311dab8142820a4f4/download',
    image: USFetusThumbnail,
    defaults: {
      colorPreset: 'US-Fetal',
    },
  },
  {
    name: 'Ultrasound Cine',
    filename: 'US_multiframe_30frames.dcm',
    description: '30-frame echocardiogram with cine playback. (225 KB)',
    url: 'https://raw.githubusercontent.com/pydicom/pydicom/v3.0.1/src/pydicom/data/test_files/examples_ybr_color.dcm',
    image: USCineThumbnail,
  },
];

/**
 * Demographics for the sample datasets, so they can be triaged from the
 * worklist before they are downloaded. The imaging is real; the patients,
 * accession numbers and readers are invented.
 */
export const SAMPLE_WORKLIST_METADATA: Record<string, SampleWorklistMetadata> =
  {
    'CTA Head and Neck': {
      patientName: 'Whitfield^Eleanor^R',
      patientId: 'PVV-100482',
      patientBirthDate: '19470312',
      patientSex: 'F',
      accessionNumber: 'ACC-2291045',
      modality: 'CT',
      description: 'CTA Head and Neck with contrast',
      bodyPart: 'HEADNECK',
      daysAgo: 0,
      time: '074512',
      priority: 'stat',
      readStatus: 'unread',
      assignedReader: 'Dr. A. Vermeer',
      series: [
        {
          seriesNumber: '1',
          description: 'CTA arterial 0.6 mm',
          modality: 'CT',
          imageCount: 512,
        },
      ],
    },
    'MRA Head and Neck': {
      patientName: 'Okonkwo^Daniel',
      patientId: 'PVV-100517',
      patientBirthDate: '19680924',
      patientSex: 'M',
      accessionNumber: 'ACC-2291102',
      modality: 'MR',
      description: 'MRA Circle of Willis',
      bodyPart: 'HEAD',
      daysAgo: 1,
      time: '113005',
      priority: 'routine',
      readStatus: 'unread',
      assignedReader: 'Dr. A. Vermeer',
      series: [
        {
          seriesNumber: '1',
          description: 'MRA TOF 3D',
          modality: 'MR',
          imageCount: 176,
        },
      ],
    },
    'MRI Cardiac 3D and Cine': {
      patientName: 'Bergstrom^Lena',
      patientId: 'PVV-100633',
      patientBirthDate: '19790105',
      patientSex: 'F',
      accessionNumber: 'ACC-2291338',
      modality: 'MR',
      description: 'Cardiac MRI 3D and cine',
      bodyPart: 'HEART',
      daysAgo: 1,
      time: '161540',
      priority: 'routine',
      readStatus: 'in-progress',
      assignedReader: 'Dr. M. Haddad',
      series: [
        {
          seriesNumber: '1',
          description: 'Whole heart 3D',
          modality: 'MR',
          imageCount: 54,
        },
        {
          seriesNumber: '2',
          description: 'Cine SSFP short axis',
          modality: 'MR',
          imageCount: 30,
        },
      ],
    },
    'MRI PROSTATEx': {
      patientName: 'Castellanos^Miguel',
      patientId: 'PVV-100708',
      patientBirthDate: '19551130',
      patientSex: 'M',
      accessionNumber: 'ACC-2290877',
      modality: 'MR',
      description: 'MRI Prostate multiparametric',
      bodyPart: 'PROSTATE',
      daysAgo: 3,
      time: '092210',
      priority: 'routine',
      readStatus: 'unread',
      assignedReader: 'Dr. M. Haddad',
      series: [
        {
          seriesNumber: '1',
          description: 'T2 TSE axial',
          modality: 'MR',
          imageCount: 19,
        },
      ],
    },
    '3D US Fetus': {
      patientName: 'Nakamura^Aya',
      patientId: 'PVV-100811',
      patientBirthDate: '19960718',
      patientSex: 'F',
      accessionNumber: 'ACC-2290640',
      modality: 'US',
      description: '3D obstetric ultrasound',
      bodyPart: 'ABDOMEN',
      daysAgo: 5,
      time: '134420',
      priority: 'routine',
      readStatus: 'read',
      assignedReader: 'Dr. S. Nkemelu',
      series: [
        {
          seriesNumber: '1',
          description: '3D volume sweep',
          modality: 'US',
          imageCount: 1,
        },
      ],
    },
    'Ultrasound Cine': {
      patientName: 'Doyle^Patrick^J',
      patientId: 'PVV-100924',
      patientBirthDate: '19610203',
      patientSex: 'M',
      accessionNumber: 'ACC-2290512',
      modality: 'US',
      description: 'Transthoracic echocardiogram',
      bodyPart: 'HEART',
      daysAgo: 8,
      time: '101755',
      priority: 'routine',
      readStatus: 'read',
      assignedReader: 'Dr. S. Nkemelu',
      series: [
        {
          seriesNumber: '1',
          description: 'Apical 4-chamber cine',
          modality: 'US',
          imageCount: 30,
        },
      ],
    },
  };

/**
 * Fabricated worklist rows. Nothing here is backed by pixel data — the UI
 * labels them as demo entries and offers a sample dataset instead of
 * pretending to open something.
 */
export const WORKLIST_DEMO_STUDIES: SyntheticWorklistStudy[] = [
  {
    key: 'demo-1',
    patientName: 'Al-Rashid^Nadia',
    patientId: 'PVV-101033',
    patientBirthDate: '19731122',
    patientSex: 'F',
    accessionNumber: 'ACC-2291410',
    modality: 'CT',
    description: 'CT Pulmonary angiogram',
    bodyPart: 'CHEST',
    daysAgo: 0,
    time: '061205',
    priority: 'stat',
    readStatus: 'unread',
    assignedReader: 'Dr. A. Vermeer',
    series: [
      {
        seriesNumber: '1',
        description: 'Scout',
        modality: 'CT',
        imageCount: 2,
      },
      {
        seriesNumber: '2',
        description: 'Arterial phase 1.0 mm',
        modality: 'CT',
        imageCount: 512,
      },
      {
        seriesNumber: '3',
        description: 'Coronal MPR 3.0 mm',
        modality: 'CT',
        imageCount: 228,
      },
    ],
  },
  {
    key: 'demo-2',
    patientName: 'Fitzgerald^Rowan',
    patientId: 'PVV-101044',
    patientBirthDate: '19901007',
    patientSex: 'M',
    accessionNumber: 'ACC-2291398',
    modality: 'CT',
    description: 'CT Head without contrast',
    bodyPart: 'HEAD',
    daysAgo: 0,
    time: '032640',
    priority: 'stat',
    readStatus: 'in-progress',
    assignedReader: 'Dr. L. Fontaine',
    series: [
      {
        seriesNumber: '1',
        description: 'Axial 0.9 mm',
        modality: 'CT',
        imageCount: 288,
      },
      {
        seriesNumber: '2',
        description: 'Bone kernel',
        modality: 'CT',
        imageCount: 22,
      },
    ],
  },
  {
    key: 'demo-3',
    patientName: 'Sorensen^Ingrid',
    patientId: 'PVV-101090',
    patientBirthDate: '19511219',
    patientSex: 'F',
    accessionNumber: 'ACC-2291371',
    modality: 'MG',
    description: 'Bilateral screening mammogram',
    bodyPart: 'BREAST',
    daysAgo: 1,
    time: '084500',
    priority: 'routine',
    readStatus: 'unread',
    assignedReader: 'Dr. L. Fontaine',
    series: [
      { seriesNumber: '1', description: 'R CC', modality: 'MG', imageCount: 1 },
      { seriesNumber: '2', description: 'L CC', modality: 'MG', imageCount: 1 },
      {
        seriesNumber: '3',
        description: 'R MLO',
        modality: 'MG',
        imageCount: 1,
      },
      {
        seriesNumber: '4',
        description: 'L MLO',
        modality: 'MG',
        imageCount: 1,
      },
    ],
  },
  {
    key: 'demo-4',
    patientName: 'Ferreira^Joao^P',
    patientId: 'PVV-101122',
    patientBirthDate: '19660430',
    patientSex: 'M',
    accessionNumber: 'ACC-2291344',
    modality: 'PT',
    description: 'FDG PET/CT whole body',
    bodyPart: 'WHOLEBODY',
    daysAgo: 2,
    time: '105320',
    priority: 'routine',
    readStatus: 'unread',
    assignedReader: 'Dr. M. Haddad',
    series: [
      {
        seriesNumber: '1',
        description: 'CT attenuation correction',
        modality: 'CT',
        imageCount: 545,
      },
      {
        seriesNumber: '2',
        description: 'PET AC whole body',
        modality: 'PT',
        imageCount: 545,
      },
      {
        seriesNumber: '3',
        description: 'MIP',
        modality: 'PT',
        imageCount: 18,
      },
    ],
  },
  {
    key: 'demo-5',
    patientName: 'Mbeki^Thandiwe',
    patientId: 'PVV-101178',
    patientBirthDate: '19850215',
    patientSex: 'F',
    accessionNumber: 'ACC-2291280',
    modality: 'MR',
    description: 'MRI Lumbar spine without contrast',
    bodyPart: 'LSPINE',
    daysAgo: 2,
    time: '143012',
    priority: 'routine',
    readStatus: 'in-progress',
    assignedReader: 'Dr. S. Nkemelu',
    series: [
      {
        seriesNumber: '1',
        description: 'Sag T1',
        modality: 'MR',
        imageCount: 15,
      },
      {
        seriesNumber: '2',
        description: 'Sag T2',
        modality: 'MR',
        imageCount: 15,
      },
      {
        seriesNumber: '3',
        description: 'Sag STIR',
        modality: 'MR',
        imageCount: 15,
      },
      {
        seriesNumber: '4',
        description: 'Ax T2 L3-S1',
        modality: 'MR',
        imageCount: 120,
      },
      {
        seriesNumber: '5',
        description: 'Localizer',
        modality: 'MR',
        imageCount: 45,
      },
    ],
  },
  {
    key: 'demo-6',
    patientName: 'Kowalski^Piotr',
    patientId: 'PVV-101201',
    patientBirthDate: '19430608',
    patientSex: 'M',
    accessionNumber: 'ACC-2291255',
    modality: 'CR',
    description: 'Chest radiograph PA and lateral',
    bodyPart: 'CHEST',
    daysAgo: 3,
    time: '071940',
    priority: 'routine',
    readStatus: 'read',
    assignedReader: 'Dr. A. Vermeer',
    series: [
      { seriesNumber: '1', description: 'PA', modality: 'CR', imageCount: 1 },
      {
        seriesNumber: '2',
        description: 'Lateral',
        modality: 'CR',
        imageCount: 1,
      },
    ],
  },
  {
    key: 'demo-7',
    patientName: 'Delacroix^Amelie',
    patientId: 'PVV-101266',
    patientBirthDate: '19980921',
    patientSex: 'F',
    accessionNumber: 'ACC-2291190',
    modality: 'CT',
    description: 'CT Abdomen and pelvis with contrast',
    bodyPart: 'ABDOMEN',
    daysAgo: 4,
    time: '191505',
    priority: 'stat',
    readStatus: 'read',
    assignedReader: 'Dr. L. Fontaine',
    series: [
      {
        seriesNumber: '1',
        description: 'Portal venous 1.25 mm',
        modality: 'CT',
        imageCount: 640,
      },
      {
        seriesNumber: '2',
        description: 'Coronal 3.0 mm',
        modality: 'CT',
        imageCount: 120,
      },
      {
        seriesNumber: '3',
        description: 'Sagittal 3.0 mm',
        modality: 'CT',
        imageCount: 66,
      },
    ],
  },
  {
    key: 'demo-8',
    patientName: 'Hoffmann^Klaus',
    patientId: 'PVV-101310',
    patientBirthDate: '19590812',
    patientSex: 'M',
    accessionNumber: 'ACC-2291121',
    modality: 'MR',
    description: 'MRI Brain with and without contrast',
    bodyPart: 'BRAIN',
    daysAgo: 6,
    time: '120030',
    priority: 'routine',
    readStatus: 'unread',
    assignedReader: 'Dr. M. Haddad',
    series: [
      {
        seriesNumber: '1',
        description: 'Ax T1',
        modality: 'MR',
        imageCount: 60,
      },
      {
        seriesNumber: '2',
        description: 'Ax T2 FLAIR',
        modality: 'MR',
        imageCount: 60,
      },
      {
        seriesNumber: '3',
        description: 'Ax DWI',
        modality: 'MR',
        imageCount: 60,
      },
      {
        seriesNumber: '4',
        description: 'Ax ADC',
        modality: 'MR',
        imageCount: 60,
      },
      {
        seriesNumber: '5',
        description: 'Ax SWI',
        modality: 'MR',
        imageCount: 84,
      },
      {
        seriesNumber: '6',
        description: 'Ax T1 post',
        modality: 'MR',
        imageCount: 60,
      },
    ],
  },
  {
    key: 'demo-9',
    patientName: 'Petrov^Irina',
    patientId: 'PVV-101377',
    patientBirthDate: '19881103',
    patientSex: 'F',
    accessionNumber: 'ACC-2291066',
    modality: 'US',
    description: 'Ultrasound right upper quadrant',
    bodyPart: 'ABDOMEN',
    daysAgo: 9,
    time: '154210',
    priority: 'routine',
    readStatus: 'read',
    assignedReader: 'Dr. S. Nkemelu',
    series: [
      {
        seriesNumber: '1',
        description: 'RUQ survey',
        modality: 'US',
        imageCount: 24,
      },
    ],
  },
  {
    key: 'demo-10',
    patientName: 'Yamamoto^Kenji',
    patientId: 'PVV-101402',
    patientBirthDate: '19701229',
    patientSex: 'M',
    accessionNumber: 'ACC-2290998',
    modality: 'DX',
    description: 'Right knee series',
    bodyPart: 'KNEE',
    daysAgo: 12,
    time: '093315',
    priority: 'routine',
    readStatus: 'read',
    assignedReader: 'Dr. A. Vermeer',
    series: [
      { seriesNumber: '1', description: 'AP', modality: 'DX', imageCount: 1 },
      {
        seriesNumber: '2',
        description: 'Lateral',
        modality: 'DX',
        imageCount: 1,
      },
      {
        seriesNumber: '3',
        description: 'Sunrise',
        modality: 'DX',
        imageCount: 1,
      },
    ],
  },
  {
    key: 'demo-11',
    patientName: 'Novak^Eva',
    patientId: 'PVV-101455',
    patientBirthDate: '19620527',
    patientSex: 'F',
    accessionNumber: 'ACC-2290901',
    modality: 'CT',
    description: 'CT Chest low dose screening',
    bodyPart: 'CHEST',
    daysAgo: 18,
    time: '081040',
    priority: 'routine',
    readStatus: 'read',
    assignedReader: 'Dr. L. Fontaine',
    series: [
      {
        seriesNumber: '1',
        description: 'Axial 1.0 mm lung kernel',
        modality: 'CT',
        imageCount: 380,
      },
      {
        seriesNumber: '2',
        description: 'Coronal 3.0 mm',
        modality: 'CT',
        imageCount: 86,
      },
    ],
  },
  {
    key: 'demo-12',
    patientName: 'Adeyemi^Folasade',
    patientId: 'PVV-101488',
    patientBirthDate: '19940814',
    patientSex: 'F',
    accessionNumber: 'ACC-2290844',
    modality: 'MR',
    description: 'MR Enterography',
    bodyPart: 'ABDOMEN',
    daysAgo: 25,
    time: '132250',
    priority: 'routine',
    readStatus: 'unread',
    assignedReader: 'Dr. M. Haddad',
    series: [
      {
        seriesNumber: '1',
        description: 'Cor HASTE',
        modality: 'MR',
        imageCount: 72,
      },
      {
        seriesNumber: '2',
        description: 'Ax HASTE',
        modality: 'MR',
        imageCount: 72,
      },
      {
        seriesNumber: '3',
        description: 'Cor VIBE post',
        modality: 'MR',
        imageCount: 72,
      },
      {
        seriesNumber: '4',
        description: 'Ax DWI',
        modality: 'MR',
        imageCount: 72,
      },
    ],
  },
];

export const TOOL_COLORS = [
  '#58f24c',
  '#8de4d3',
  '#f0a4b1',
  '#a3c9fe',
  '#c8f251',
  '#fea53b',
];

export const STROKE_WIDTH_ANNOTATION_TOOL_DEFAULT = 1;

export const RULER_LABEL_DEFAULTS = {
  'Label 1': { color: 'red' },
};

export const RECTANGLE_LABEL_DEFAULTS = {
  'Label 1': { color: 'red' },
};

export const POLYGON_LABEL_DEFAULTS = {
  'Label 1': { color: 'red' },
};

export const DEFAULT_PRESET_BY_MODALITY: Record<string, string> = {
  CT: 'CT-AAA',
  MR: 'CT-Coronary-Arteries-2',
  US: 'US-Fetal',
};
export const DEFAULT_PRESET = 'CT-AAA';

export const LAYER_PRESET_BY_MODALITY: Record<string, string> = {
  ...DEFAULT_PRESET_BY_MODALITY,
  PT: '2hot-opaque',
};
export const LAYER_PRESET_DEFAULT = '2hot-opaque';

// Keyboard shortcuts/hotkeys. Can add modifiers: 'Shift+Ctrl+a'
export const ACTION_TO_KEY = {
  windowLevel: 'l',
  pan: 'n',
  zoom: 'z',
  ruler: 'm',
  paint: 'p',
  paintEraser: 'e',
  brushSizeModifier: 'ctrl',
  decreaseBrushSize: '[',
  increaseBrushSize: ']',
  rectangle: 'r',
  crosshairs: 'c',
  temporaryCrosshairs: 'shift-c',
  crop: 'b',
  polygon: 'g',
  mergeNewPolygon: 'Shift',
  select: 's',

  nextSlice: 'arrowdown',
  previousSlice: 'arrowup',
  grabSlice: 'Alt',

  decrementLabel: 'q',
  incrementLabel: 'w',

  deleteCurrentImage: 'ctrl+.',
  clearScene: 'ctrl+/',

  showKeyboardShortcuts: '?',
} satisfies Record<Action, string>;

export const DEFAULT_SEGMENT_MASKS: SegmentMask[] = [
  {
    value: 1,
    name: 'Segment 1',
    color: [255, 255, 0, 255],
    visible: true,
  },
];

// from https://github.com/InsightSoftwareConsortium/itk-viewer-color-maps/blob/main/src/CategoricalColors.json
export const CATEGORICAL_COLORS = [
  [214, 0, 0],
  [59, 255, 1],
  [0, 0, 172],
  [151, 255, 0],
  [126, 209, 107],
  [79, 255, 165],
  [87, 59, 0],
  [86, 89, 0],
  [221, 0, 253],
  [161, 117, 105],
  [182, 255, 149],
  [119, 191, 3],
  [100, 84, 116],
  [0, 0, 7],
  [216, 253, 244],
  [0, 75, 0],
  [121, 0, 255],
  [102, 237, 184],
  [93, 126, 102],
  [228, 255, 235],
  [119, 165, 123],
  [89, 0, 163],
  [198, 0, 158],
  [0, 156, 59],
  [202, 195, 0],
  [130, 151, 0],
  [137, 130, 135],
  [93, 54, 59],
  [0, 0, 253],
  [255, 189, 230],
  [219, 109, 1],
  [184, 181, 228],
  [255, 47, 82],
  [195, 102, 144],
  [98, 31, 196],
  [114, 3, 130],
  [105, 230, 128],
  [38, 144, 109],
  [255, 77, 51],
  [133, 163, 1],
  [3, 202, 193],
  [196, 196, 86],
  [117, 87, 61],
  [103, 66, 0],
  [212, 218, 223],
  [249, 255, 0],
  [103, 175, 195],
  [0, 225, 205],
  [218, 149, 255],
  [3, 253, 145],
  [130, 160, 0],
  [86, 154, 84],
  [140, 142, 54],
  [38, 151, 165],
  [142, 140, 94],
  [70, 0, 200],
  [249, 174, 109],
  [110, 207, 167],
  [255, 140, 140],
  [177, 119, 54],
  [255, 160, 121],
  [0, 31, 255],
  [68, 94, 17],
  [103, 151, 147],
  [94, 147, 75],
  [116, 82, 145],
  [170, 112, 49],
  [207, 253, 0],
  [107, 96, 52],
  [144, 212, 47],
  [212, 124, 80],
  [161, 77, 35],
  [124, 89, 0],
  [205, 68, 130],
  [207, 77, 253],
  [137, 0, 61],
  [82, 91, 0],
  [156, 170, 130],
  [128, 112, 142],
  [100, 253, 195],
  [137, 205, 40],
  [255, 154, 181],
  [93, 186, 33],
  [1, 0, 142],
  [98, 128, 35],
  [135, 191, 151],
  [212, 205, 126],
  [209, 182, 91],
  [0, 110, 153],
  [68, 175, 198],
  [242, 255, 209],
  [235, 1, 205],
  [188, 68, 0],
  [121, 156, 126],
  [112, 70, 147],
  [186, 0, 84],
  [172, 147, 235],
  [163, 22, 94],
  [128, 0, 75],
  [124, 184, 211],
  [42, 0, 56],
  [100, 184, 0],
  [255, 128, 61],
  [209, 232, 128],
  [89, 33, 52],
  [161, 93, 110],
  [181, 175, 158],
  [70, 51, 124],
  [193, 65, 0],
  [232, 61, 107],
  [232, 117, 188],
  [165, 196, 168],
  [84, 110, 216],
  [56, 251, 124],
  [75, 100, 73],
  [195, 235, 121],
  [54, 75, 142],
  [70, 135, 255],
  [0, 195, 233],
  [212, 255, 188],
  [70, 72, 0],
  [198, 255, 144],
  [233, 79, 105],
  [230, 93, 177],
  [144, 175, 87],
  [42, 175, 93],
  [133, 109, 225],
  [110, 114, 228],
  [226, 184, 182],
  [56, 45, 0],
  [126, 163, 172],
  [47, 168, 186],
  [105, 181, 130],
  [209, 144, 175],
  [70, 7, 94],
  [0, 151, 137],
  [15, 1, 91],
  [128, 47, 87],
  [228, 100, 59],
  [63, 40, 114],
  [188, 75, 82],
  [200, 121, 221],
  [49, 144, 200],
  [242, 5, 170],
  [167, 107, 154],
  [175, 0, 96],
  [98, 242, 221],
  [119, 68, 1],
  [36, 65, 103],
  [202, 121, 158],
  [12, 232, 161],
  [247, 219, 131],
  [117, 142, 109],
  [226, 65, 47],
  [73, 107, 121],
  [133, 255, 207],
  [75, 93, 198],
  [179, 145, 255],
  [237, 214, 239],
  [191, 96, 38],
  [163, 181, 188],
  [0, 135, 110],
  [255, 47, 161],
  [232, 175, 51],
  [75, 184, 140],
  [107, 135, 82],
  [147, 209, 26],
  [253, 161, 59],
  [163, 80, 168],
  [0, 151, 137],
  [123, 89, 87],
  [249, 142, 138],
  [214, 124, 112],
  [1, 24, 89],
  [22, 38, 255],
  [216, 86, 247],
  [253, 121, 149],
  [177, 167, 212],
  [207, 221, 0],
  [175, 121, 70],
  [218, 255, 230],
  [5, 177, 242],
  [255, 163, 228],
  [137, 19, 35],
  [103, 130, 232],
  [112, 216, 170],
  [223, 186, 212],
  [82, 105, 117],
  [154, 151, 51],
  [228, 114, 126],
  [89, 38, 119],
  [105, 47, 61],
] as const;
